ENVIRONMENT:
    MAX_EPISODE_STEPS: 150

SIMULATOR:
  TYPE: Ant-v2-sim
  AGENTS: ['AGENT_0']
  AGENT_0:  
    # Agent setup
    HEIGHT: 1.5
    IS_SET_START_STATE: False
    RADIUS: 0.1
    SENSORS: ['HEAD_RGB_SENSOR', 'DEPTH_SENSOR', 'THIRD_SENSOR']
    START_POSITION: [0, -0.2, 0]
    START_ROTATION: [0, 0, 1.6, 1]
  HEAD_RGB_SENSOR:
        WIDTH: 128
        HEIGHT: 128
  THIRD_SENSOR:
        WIDTH: 512
        HEIGHT: 512
        POSITION: [-2,2,0]
        HFOV: 90
        ORIENTATION: [-0.5, -1.57,0.0]
  DEPTH_SENSOR:
        WIDTH: 128
        HEIGHT: 128
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: True
  LEG_REST: [0.0, -1.0, 0.0, -1.0, 0.0, 1.0, 0.0, 1.0] # not being used at the moment
  ROBOT_URDF: data/robots/ant.urdf
  
  #NOTE: control frequency in Hz. Physics stepped at 1/CTRL_FREQ
  CTRL_FREQ: 30
  
  #NOTE: these below are unused
  #AC_FREQ_RATIO: 4

  # LOAD_OBSTACLES: True # Loads obstacles for the ant to avoid

  HABITAT_SIM_V0:
    ALLOW_SLIDING: True
    ENABLE_PHYSICS: True
    GPU_DEVICE_ID: 0
    GPU_GPU: False
    PHYSICS_CONFIG_FILE: ./data/default.physics_config.json

TASK:
  TYPE: Ant-v2-task
  ANT_OBSERVATION_SPACE_SENSOR:
        TYPE: "AntObservationSpaceSensor"
  SENSORS: ["ANT_OBSERVATION_SPACE_SENSOR"]

  X_LOCATION:
    TYPE: "XLocation"
  VECTOR_ROOT_DELTA:
    TYPE: "VectorRootDelta"
  JOINT_STATE_ERROR:
    TYPE: "JointStateError"
    #normalize return such that max error is -1 using joint limits 
    NORMALIZED: False
  JOINT_STATE_MAX_ERROR:
    TYPE: "JointStateMaxError"
  JOINT_STATE_PRODUCT_ERROR:
    #measure is the product of inverted normalized terms (i.e. max for each joint is 1, min is 0, total is product) 
    TYPE: "JointStateProductError"
  ACTIVE_CONTACTS:
    TYPE: "ActiveContacts"
  ACTION_COST:
    TYPE: "ActionCost"
  COMPOSITE_ANT_REWARD:
    TYPE: "CompositeAntReward"
    #setting up the defaults here
    COMPONENTS: ["ACTION_COST","JOINT_STATE_ERROR","X_LOCATION"]
    WEIGHTS: [1.0, 1.0, 10.0]
  #NOTE: modify the active MEASUREMENTS below corresponding to task
  MEASUREMENTS: ["X_LOCATION", "JOINT_STATE_ERROR"]

  ACTIONS:
    LEG_ACTION:
      TYPE: "LegAction"
      LEG_CONTROLLER: "LegRelPosAction"
      LEG_JOINT_DIMENSIONALITY: 8
      DELTA_POS_LIMIT: 0.1
    LEG_ACTION_SYMMETRICAL:
      TYPE: "LegAction"
      LEG_CONTROLLER: "LegRelPosActionSymmetrical"
      LEG_JOINT_DIMENSIONALITY: 4
      DELTA_POS_LIMIT: 0.1
  POSSIBLE_ACTIONS:
    - LEG_ACTION

DATASET:
  TYPE: AntV2Dataset-v0